"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { ArrowUpRight, Github } from "lucide-react";

const projects = [
  { title: "Ebook Store", image: "/images/ebook.png", description: "A full-stack commerce platform with public and private routes, admin controls, authorization, and order tracking.", stack: ["MongoDB", "Express", "React", "Node"], github: "https://github.com/mustafaaly7/Mern-Ecommerce-Frontend", demo: "https://mern-ecommerce-frontend-murex.vercel.app/", featured: true },
  { title: "Chat App", image: "/images/chatApp.png", description: "Real-time messaging built with the MERN stack and Socket.io, deployed across Render and Vercel.", stack: ["MERN", "Socket.io", "DaisyUI"], github: "https://github.com/mustafaaly7/Chat-App", demo: "https://chatty-black-omega.vercel.app/" },
  { title: "Ecommerce Website", image: "/images/ecommerce.png", description: "A responsive storefront experience powered by React, Firebase, Tailwind CSS, and the DummyJSON API.", stack: ["React", "Firebase", "Tailwind"], github: "https://github.com/mustafaaly7/Ecommerce-demo", demo: "https://ecommerce-demo-self.vercel.app/" },
  { title: "Virtual Assistant", image: "/images/va.png", description: "A browser-based voice assistant using JavaScript and speech synthesis to understand and respond to commands.", stack: ["HTML", "CSS", "JavaScript"], github: "https://github.com/mustafaaly7/virtual-assistant-on-js", demo: "https://virtual-assistant-two.vercel.app/" },
];

function ProjectCard({ project, index }) {
  return <motion.article initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className={`${project.featured ? "lg:col-span-2" : ""} group border border-[#1F2937] bg-[#0B0F0B] transition-colors hover:border-[#22C55E]/60`}><div className={`${project.featured ? "md:grid-cols-[1.15fr_0.85fr]" : ""} grid h-full`}><div className="relative min-h-[240px] overflow-hidden border-b border-[#1F2937] bg-[#141A14] md:border-b-0 md:border-r"><Image src={project.image} alt={project.title} fill className="object-contain p-5 transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 bg-[#000000]/80 px-2 py-1 font-mono text-[10px] text-[#22C55E]">0{index + 1}</span></div><div className="flex flex-col justify-between p-6 lg:p-8"><div><div className="mb-5 flex items-start justify-between gap-4"><h3 className="font-display text-2xl font-semibold tracking-[-0.04em] text-[#E2E8F0]">{project.title}</h3><ArrowUpRight size={20} className="shrink-0 text-[#22C55E] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div><p className="text-sm leading-7 text-[#8F9B8F]">{project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.stack.map((item) => <span key={item} className="bg-[#141A14] px-2 py-1 font-mono text-[10px] uppercase tracking-[0.06em] text-[#8F9B8F]">{item}</span>)}</div></div><div className="mt-8 flex items-center gap-5 border-t border-[#1F2937] pt-5 font-mono text-[10px] uppercase tracking-[0.08em]"><a href={project.demo} target="_blank" rel="noopener noreferrer" className="text-[#22C55E]">Live demo <ArrowUpRight className="inline" size={13} /></a><a href={project.github} target="_blank" rel="noopener noreferrer" className="text-[#8F9B8F] transition-colors hover:text-[#E2E8F0]"><Github className="mr-1 inline" size={13} /> Source</a></div></div></div></motion.article>;
}

export default function Projects() {
  return <section id="projects" className="border-b border-[#1F2937] bg-black py-24 text-[#E2E8F0]"><div className="shell"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="eyebrow">02 / selected work</span><h2 className="section-heading mt-5">Things I&apos;ve shipped.</h2></div><p className="max-w-xs text-sm leading-6 text-[#8F9B8F]">A selection of products, experiments, and systems built across the stack.</p></div><div className="grid gap-5 md:grid-cols-2">{projects.map((project, index) => <ProjectCard key={project.title} project={project} index={index} />)}</div></div></section>;
}
